name: On issue comment
on:
  issue_comment:
    types: [created]
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    # if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:atlantis

      - name: Create payload
        run: |
          echo '''
          {
            "action": "created",
            "issue": {
            },
            "comment": {
            },
            "repository": {
            },
            "sender": {
            }
          }
          ''' > payload.json

      - name: Create signature
        id: signature
        run: |
          # data="$(cat payload.json)"
          data="Hello, World!"
          secret="It's a Secret to Everybody"
          sha1=$(echo -n "$data" | openssl dgst -sha1 -hmac "${{ secrets.ATLANTIS_SECRET }}" | awk '{print $2}')
          sha256=$(echo -n "$data" | openssl dgst -sha256 -hmac "${{ secrets.ATLANTIS_SECRET }}" | awk '{print $2}')

          echo "sha1=$sha1" >> $GITHUB_OUTPUT
          echo "sha256=$sha256" >> $GITHUB_OUTPUT

      - run: |
          curl -X POST \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -H 'User-Agent: GitHub-Hookshot/68d5600' \
            -H 'X-GitHub-Event: issue_comment' \
            -H 'X-Hub-Signature: sha1=${{ steps.signature.outputs.sha1 }}' \
            -H 'X-Hub-Signature-256: sha256=${{ steps.signature.outputs.sha256 }}' \
            -v \
            --data "Hello, World!" \
            --location http://188.245.227.86:4141/events
