name: Send Webhook
on:
  push: {}
  pull_request:
    types: [opened, reopened, synchronize, closed]
  pull_request_review: {}
  issue_comment: {}

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: "${{ toJSON(github.event) }}"
    # if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:atlantis

      - name: Print payload
        run: echo $PAYLOAD

      - name: Send webhook
        run: |
          USER_AGENT=$(openssl rand -hex 7)
          UUID=$(openssl rand -hex 16)
          REQUEST_ID=$(echo ${UUID:0:8}-${UUID:8:4}-${UUID:12:4}-${UUID:16:4}-${UUID:20:12})
          SHA1=$(echo -n "$PAYLOAD" | openssl dgst -sha1 -hmac '${{secrets.WEBHOOK_SECRET}}' | sed 's/.*= //')
          SHA256=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac '${{secrets.WEBHOOK_SECRET}}' | sed 's/.*= //')

          echo "user agent: $USER_AGENT"
          echo "request id: $REQUEST_ID"
          echo "sha1: $SHA1"
          echo "sha256: $SHA256"
          echo "event name: ${{ github.event_name }}"

          # curl -X POST \
          #   -H 'Content-Type: application/x-www-form-urlencoded' \
          #   -H 'User-Agent: GitHub-Hookshot/68d5600' \
          #   -H 'X-GitHub-Event: issue_comment' \
          #   -H 'X-Hub-Signature: sha1=${{ steps.signature.outputs.sha1 }}' \
          #   -H 'X-Hub-Signature-256: sha256=${{ steps.signature.outputs.sha256 }}' \
          #   -v \
          #   --data "Hello, World!" \
          #   --location http://188.245.227.86:4141/events
