name: Send Webhook
on:
  push: {}
  pull_request:
    types: [opened, reopened, synchronize, closed]
  pull_request_review: {}
  issue_comment: {}

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      WEBHOOK: "${{ toJSON(github.event) }}"
    # if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:atlantis

      - run: echo $WEBHOOK

      # - run: |
      #     curl -X POST \
      #       -H 'Content-Type: application/x-www-form-urlencoded' \
      #       -H 'User-Agent: GitHub-Hookshot/68d5600' \
      #       -H 'X-GitHub-Event: issue_comment' \
      #       -H 'X-Hub-Signature: sha1=${{ steps.signature.outputs.sha1 }}' \
      #       -H 'X-Hub-Signature-256: sha256=${{ steps.signature.outputs.sha256 }}' \
      #       -v \
      #       --data "Hello, World!" \
      #       --location http://188.245.227.86:4141/events
